config/routes.rb
Soccer5s::Application.routes.draw do

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, :at => '/'


  resources :clients, :only => [:new, :index, :show, :create]

  root :to => "public#home"
  match '/what', :to => 'public#what'
  match '/facilities', :to => 'public#facilities'
  match '/events', :to => 'public#events'
  match '/training', :to => 'public#training'
  match '/competition', :to => 'public#competition', :as => 'comp'
  match '/about', :to => 'public#about'

  resource :contact, :only => [:new, :show, :create]

  resources :competitions do
    collection do
      get 'terms'
      get 'entry'
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  
  validates :email, :presence => true, 
    :length => {:minimum => 3, :maximum => 254},
    :uniqueness => true,
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}  
    
  attr_accessible :email
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  
  validates :name, :presence => true
  validates :email, :presence => true, 
    :length => {:minimum => 3, :maximum => 254},
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  # validates_acceptance_of :terms, :accept => [true, "1", "true"]
  validates_presence_of :team_name
    
  after_create :send_mail
  
  attr_accessible :name, :email, :terms, :team_name, :favorite_mariner, :telephone, :comments, :subject
  attr_accessor :terms_and_conditions
  
  private
  
  def send_mail
    CompetitionMailer.client_email(self).deliver
    CompetitionMailer.admin_email(self).deliver
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :name, :presence => true
  validates :email, :presence => true,
    :length => {:minimum => 3, :maximum => 254},
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  attr_accessible :email, :name, :telephone, :message, :subject

  # Email message subject...  I don't care that this doesn't belong here
  attr_accessor :subject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/new
  def new
    @client = Client.new
  end
  
  # GET /clients/1
  def show
    # @client = Client.find(params[:id]) rescue Client.first
  end

  # POST /clients
  def create
    @client = Client.new(params[:client])

    if @client.save
      ClientMailer.client_email(@client).deliver
      ClientMailer.admin_email(@client).deliver
      redirect_to @client
    else
      render :action => "new"
    end
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  # GET /competitions
  # GET /competitions.xml
  def index
    @competitions = Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.xml
  def show
    @competition = Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.xml
  def new
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @competition }
    end
  end
  
  def entry
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @competition }
    end
  end
  
  # GET /competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.xml
  def create
    @competition = Competition.new(params[:competition])
    
    respond_to do |format|
      if @competition.save
        format.html { redirect_to(@competition, :notice => 'Competition was successfully entered.') }
        format.xml  { render :xml => @competition, :status => :created, :location => @competition }
      else
        format.html { render :action => @competition.subject ? "entry" : "new" }    # dumb, for now use subject for new mariner's competition
        format.xml  { render :xml => @competition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.xml
  def update
    @competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to(@competition, :notice => 'Competition was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @competition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.xml
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to(competitions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new params[:contact]
  end

  def show; end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      ClientMailer.client_email(@contact).deliver
      ClientMailer.admin_email(@contact).deliver
      redirect_to contact_path(:anchor => 'form')
    else
      render :action => 'new'
    end
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  def home; end  
  def what; end
  def facilities; end
  def events; end
  def training; end
  def competition; end
  def about; end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def section
    controller_name.underscore
  end

  def id
    action_name.underscore
  end

  def body(&block)
    content_tag(:div, id: 'body', &block)
  end

  def main(&block)
    content_tag(:section, id: 'main', &block)
  end

  def sidebar(&block)
    content_tag(:section, id: 'sidebar', &block)
  end

  def random_banner
    (home_page? ? home_banners : page_banners).sample
  end

private

  def page_banners
    %w{one two three four five six seven eight nine}
  end

  def home_banners
    %w{one two three}
  end
end

app/helpers/carousel_helper.rb
module CarouselHelper
  # Super dumb implementation to convert numbers to words
  # we don't need anything greater than 10 anyway
  def carousel_page(number)
    {
      1 => 'one',
      2 => 'two',
      3 => 'three',
      4 => 'four',
      5 => 'five',
      6 => 'six',
      7 => 'seven',
      8 => 'eight',
      9 => 'nine',
      10 => 'ten'
    }.fetch(number + 1, 0)
  end

  def formatted_carousel_page(number)
    "%02d" % (number + 1)
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render '/refinery/html_tag' %>
  <% site_bar = render('/refinery/site_bar', :head => true) -%>
  <%= render '/refinery/head' %>
  <body id="<%= id %>" class="<%= section %> <%= page_slug %>">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=108379095997939";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <%= site_bar -%>
    <%= render '/refinery/ie6check' if request.env['HTTP_USER_AGENT'] =~ /MSIE/ -%>
    <div id="page_container">
      <header id="header">
        <%= render '/refinery/header' -%>
      </header>

      <section id="page">
        <%= yield %>
      </section>

      <footer>
        <%= render '/refinery/footer' -%>
      </footer>
    </div>
    <%= javascript_include_tag 'http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js' %>
    <%= render '/refinery/javascripts' %>

    <!--[if lt IE 9]>
      <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
    <![endif]-->
  </body>
</html>
<%= page_slug %>

app/views/refinery/_footer.html.erb
<%= link_to t('.copyright', :year => Time.now.year, :site_name => Refinery::Core.site_name), '#' %> |
<%= link_to 'Contact', refinery.inquiries_new_inquiry_path %> |
<%= link_to 'Careers', refinery.inquiries_new_inquiry_path %> |
<%= link_to 'Corporate Site', refinery.inquiries_new_inquiry_path %>

<div class="social">
  <%= link_to image_tag('logos/facebook-icon.png'), 'http://www.facebook.com/pages/Soccer5s/124555744270317' %>
  <%= link_to image_tag('logos/twitter-icon.png'), 'http://twitter.com/soccer5s' %>
</div>

app/views/refinery/blog/posts/_post.html.erb
<% flash.each do |key, value| %>
 <div id='flash' class="flash flash_<%= key %>">
   <%= value %>
 </div>
<% end %>
<article id="blog-post">
  <header>
    <h2><%= @post.title %></h2>
    <section class='details'>
      <time datetime="<%=l @post.published_at.to_date, :format => :default %>" class='posted_at'>
        <%= t('created_at', :scope => 'refinery.blog.shared.posts', :when => l(@post.published_at.to_date, :format => :short)) %>
      </time>
      <% if @post.source_url.present? %>
        <div class='blog_source'>
          <%= "#{t('source', :scope => 'refinery.blog.posts.show')}: " %>
          <%= link_to (@post.source_url_title.blank? ? @post.source_url : @post.source_url_title), @post.source_url %>
        </div>
      <% end %>
      <% if (categories = @post.categories).any? %>
        <aside class='filed_in'>
          <%= t('filed_in', :scope => 'refinery.blog.posts.show') %>
          <% categories.each_with_index do |category, index| %>
            <%= link_to category.title, refinery.blog_category_path(category) -%><%= ',' if index < ((categories.length) - 1) %>
          <% end %>
        </aside>
      <% end %>
    </section>
  </header>
  <%= @post.body.html_safe %>

  <% if Refinery::Blog::Post::ShareThis.enabled? %>
    <span class="st_sharethis" displayText="ShareThis"></span>
  <% end %>
</article>
<%= render :partial => '/refinery/draft_page_message' unless @post.nil? or @post.live? -%>
<%= render 'nav' if next_or_previous?(@post) %>

app/views/refinery/blog/posts/index.html.erb
<%= render '/shared/banner' %>

<%= body do %>
  <%= main do %>
    <%= raw @page.content_for(Refinery::Pages.default_parts.first.to_sym) if Refinery::Pages.default_parts.any? %>

    <% if @posts.any? %>
      <section id="blog-posts" class="panes">
        <%= render :partial => "/refinery/blog/shared/post", :collection => @posts %>
        <%= will_paginate @posts %>
      </section>
    <% else %>
      <p><%= t('.no_blog_articles_yet') %></p>
    <% end %>
  <% end %>

  <%= sidebar do %>
    <% content_for :body_content_right_prepend do -%>
      <%= raw @page.content_for(Refinery::Pages.default_parts.second.to_sym) %>
    <% end if Refinery::Pages.default_parts.many? -%>
    <%= render :partial => '/refinery/blog/shared/body_content_right' %>
    <%= render :partial => "/refinery/content_page" %>
  <% end %>
<% end %>

<% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>

app/views/refinery/blog/posts/show.html.erb
<%= render '/shared/banner' %>

<%= body do %>
  <%= main do %>
    <div class="panes">
      <div id="show_blog_post">
        <%= render 'post' %>
      </div>

      <% if Refinery::Blog::Post.comments_allowed? %>
        <%= render 'comments'%>
      <% end %>
    </div>
  <% end %>

  <%= sidebar do %>
    <%= render :partial => '/refinery/blog/shared/body_content_right' %>
    <%= render :partial => "/refinery/content_page", :locals => { :remove_automatic_sections => true }  %>
  <% end %>
<% end %>


<% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>
<% content_for :javascripts do %>
  <%# enable AJAX'd post nav at your own risk until html5 history API implemented. %>
  <%#= javascript_include_tag('refinery/blog/frontend') %>
  <script src="http://w.sharethis.com/button/buttons.js"></script>
  <script>stLight.options({publisher:'<%= Blog::Post::ShareThis.key %>'});</script>
<% end if Refinery::Blog::Post::ShareThis.enabled? %>

app/views/refinery/blog/shared/_post.html.erb
<% if post.live? %>
  <article class="blog-post" id="<%= dom_id(post) %>">
    <header>
      <h2><%= link_to post.title, refinery.blog_post_path(post) %></h2>
      <section class='details'>
        <time datetime="<%=l post.published_at.to_date, :format => :default %>" class='posted_at'>
          <%= t('created_at', :scope => 'refinery.blog.shared.posts', :when => l(post.published_at.to_date, :format => :short)) %>
        </time>
        <% if (categories = post.categories).any? %>
          <aside class='filed_in'>
            <%= t('filed_in', :scope => 'refinery.blog.posts.show') %>
            <%=raw categories.collect { |category| link_to category.title, refinery.blog_category_path(category) }.to_sentence %>
          </aside>
        <% end %>
        <% if (tags = post.tags).any? %>
          <aside class='tagged'>
            <%= t('tagged', :scope => 'refinery.blog.posts.show') %>
            <%=raw tags.collect { |tag| link_to tag, refinery.blog_tagged_posts_path(tag.id, tag.name.parameterize) }.to_sentence %>
          </aside>
        <% end %>
      </section>
    </header>
    <section class='clearfix'>
      <% if blog_post_teaser_enabled? %>
        <%= blog_post_teaser(post) %>
      <% else %>
        <%= post.body.html_safe %>
      <% end %>
    </section>
    <footer>
      <p>
        <%= link_to t('read_more', :scope => 'refinery.blog.shared.posts'), refinery.blog_post_path(post) if blog_post_teaser_enabled? %>
      </p>
      <aside class='comment_count'>
        <% if Refinery::Blog::Post.comments_allowed? %>
          <% if post.comments.any? %>
             (<%= pluralize(post.comments.approved.count, t('singular', :scope => 'refinery.blog.shared.comments')) %>)
          <% else %>
                (<%= t('none', :scope => 'refinery.blog.shared.comments') %>)
          <% end %>
        <% end %>
      </aside>
    </footer>
  </article>
<% end %>

app/views/refinery/blog/shared/_post_home.html.erb
<% if post.live? %>
  <article class="blog-post" id="<%= dom_id(post) %>">
    <header>
      <h2><%= link_to post.title, refinery.blog_post_path(post) %></h2>
      <section class='details'>
        <time datetime="<%=l post.published_at.to_date, :format => :default %>" class='posted_at'>
          <%= t('created_at', :scope => 'refinery.blog.shared.posts', :when => l(post.published_at.to_date, :format => :short)) %>
        </time>
        <% if (categories = post.categories).any? %>
          <aside class='filed_in'>
            <%= t('filed_in', :scope => 'refinery.blog.posts.show') %>
            <%=raw categories.collect { |category| link_to category.title, refinery.blog_category_path(category) }.to_sentence %>
          </aside>
        <% end %>
        <% if (tags = post.tags).any? %>
          <aside class='tagged'>
            <%= t('tagged', :scope => 'refinery.blog.posts.show') %>
            <%=raw tags.collect { |tag| link_to tag, refinery.blog_tagged_posts_path(tag.id, tag.name.parameterize) }.to_sentence %>
          </aside>
        <% end %>
      </section>
    </header>
    <section class='clearfix'>
      <%# if blog_post_teaser_enabled? %>
        <%#= blog_post_teaser(post) %>
      <%# else %>
        <%= post.body.html_safe %>
      <%# end %>
    </section>
    <footer>
      <p>
        <%= link_to t('read_more', :scope => 'refinery.blog.shared.posts'), refinery.blog_post_path(post) if blog_post_teaser_enabled? %>
      </p>
      <aside class='comment_count'>
        <% if Refinery::Blog::Post.comments_allowed? %>
          <% if post.comments.any? %>
             (<%= pluralize(post.comments.approved.count, t('singular', :scope => 'refinery.blog.shared.comments')) %>)
          <% else %>
                <%= t('none', :scope => 'refinery.blog.shared.comments') %>
          <% end %>
        <% end %>
      </aside>
    </footer>
  </article>
<% end %>

app/views/refinery/blog/shared/_posts.html.erb
<% if @posts.many? %>
  <h2><%= t('.other') %></h2>
  <ul id="blog_posts">
    <% @posts.each do |blog_post| %>
      <li class='clearfix'>
        <%= link_to blog_post.title, refinery.blog_post_path(blog_post) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/refinery/inquiries/inquiries/new.html.erb
<%= render '/shared/banner' %>

<%= body do %>
  <%= main do %>
    <ul class="tabs">
      <li><a href="#form" class="current">Contact Form</a></li>
      <li><a href="#map">Location Map</a></li>
    </ul>

    <div class="panes">
      <div>
        <%=raw @page.content_for(:body) %>

        <%= simple_form_for [refinery, :inquiries, @inquiry] do |f| %>
          <%= f.input :name,  label: "Your Name <span>(required)</span>".html_safe, :required => false %>
          <%= f.input :email, label: "Email Address <span>(required)</span>".html_safe, :required => false %>
          <%= f.input :phone, label: "Telephone number <span>(required)</span>".html_safe, required: false %>
          <%= f.input :message, :as => :text, :label => "Your Message".html_safe, :required => false, :error => false %>
          <%= f.input :bot_protection, label: "Don't fill this in", wrapper_html: {style: 'display: none;'} %>

          <%= f.button :submit, :class => 'submit', :value => t('.send') %>
          <%= link_to t('.privacy_policy'), "/pages/privacy-policy", :id => "privacy_link" if Refinery::Inquiries.show_contact_privacy_link %>
        <% end %>
      </div>

      <div style="display: none;">
        <h2>Map</h2><br>
        <iframe width="580" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.ca/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Soccer5s,+Bryant+Drive,+Tuggerah,+NSW,+2259,+Australia&amp;aq=0&amp;oq=Soccer1+Bryant+Drive+Tuggerah+NSW+2259&amp;sll=-33.310948,151.422501&amp;sspn=0.012176,0.021822&amp;gl=ca&amp;ie=UTF8&amp;hq=Soccer5s,&amp;hnear=Bryant+Dr,+Tuggerah+New+South+Wales+2259,+Australia&amp;t=m&amp;cid=13412483988757976693&amp;ll=-33.290719,151.398726&amp;spn=0.025111,0.049782&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.ca/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Soccer5s,+Bryant+Drive,+Tuggerah,+NSW,+2259,+Australia&amp;aq=0&amp;oq=Soccer1+Bryant+Drive+Tuggerah+NSW+2259&amp;sll=-33.310948,151.422501&amp;sspn=0.012176,0.021822&amp;gl=ca&amp;ie=UTF8&amp;hq=Soccer5s,&amp;hnear=Bryant+Dr,+Tuggerah+New+South+Wales+2259,+Australia&amp;t=m&amp;cid=13412483988757976693&amp;ll=-33.290719,151.398726&amp;spn=0.025111,0.049782&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>
      </div>
    </div>
  <% end %>

  <%= sidebar do %>
    <%= render 'shared/fb_like_box' %>
  <% end %>
<% end %>

app/views/refinery/inquiries/inquiries/thank_you.html.erb
<%= render '/shared/banner' %>

<%= body do %>
  <%= main do %>
    <ul class="tabs">
      <li><a href="#form" class="current">Contact Form</a></li>
      <li><a href="#map">Location Map</a></li>
    </ul>

    <div class="panes">
      <div>
        <%=raw @page.content_for(:body) %>
      </div>

      <div style="display: none;">
        <h2>Map</h2><br>
        <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com.au/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Club+Tuggerah,+Bryant+Drive,+Tuggerah+&amp;aq=&amp;sll=-25.335448,135.745076&amp;sspn=49.716039,82.353516&amp;ie=UTF8&amp;hq=Club+Tuggerah,&amp;hnear=Bryant+Dr,+Tuggerah+New+South+Wales+2259&amp;ll=-33.30998,151.422908&amp;spn=0.006223,0.009141&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe><br><small><a href="http://maps.google.com.au/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Club+Tuggerah,+Bryant+Drive,+Tuggerah+&amp;aq=&amp;sll=-25.335448,135.745076&amp;sspn=49.716039,82.353516&amp;ie=UTF8&amp;hq=Club+Tuggerah,&amp;hnear=Bryant+Dr,+Tuggerah+New+South+Wales+2259&amp;ll=-33.30998,151.422908&amp;spn=0.006223,0.009141&amp;z=16&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>
      </div>
    </div>
  <% end %>

  <%= sidebar do %>
    <%= render 'shared/fb_like_box' %>
  <% end %>
<% end %>

app/views/refinery/pages/home.html.erb
<%= render '/shared/banner' %>

<% if carousel? %>
<div id="carousel">
  <div class="navi">
    <% carousel_items.each_with_index do |page, index| %>
      <%= link_to index + 1, "##{carousel_page(index)}", class: index.zero? ? "active" : "" %>
    <% end %>
  </div>

  <button class="prev browse">&lsaquo;</button>
  <div class="scrollable">
    <div class="items">
      <%= render partial: '/shared/carousel', collection: carousel_items %>
    </div>
  </div>
  <button class="next browse">&rsaquo;</button>
</div>
<% end %>

<%= body do %>
  <%= main do %>
    <div class="panes">
      <div id="show_blog_post">
        <%= render :partial => "/refinery/blog/shared/post_home", :object => Refinery::Blog::Post.latest, as: 'post' %>
      </div>
    </div>
  <% end %>

  <%= sidebar do %>
    <%= render 'shared/fb_like_box' %>
  <% end %>
<% end %>

app/views/refinery/pages/show.html.erb
<%= render '/shared/banner' %>

<%= body do %>
  <%= main do %>
    <% if nested? %>
      <ul class="tabs">
        <% pages_for_section.each do |page| %>
          <li><%= link_to page.title, refinery.url_for(page.url), class: @page == page ? "current" : "" %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="panes">
      <%= raw @page.content_for(:body) %>

      <% @page.images.each do |image| %>
        <%= link_to image_tag(image.thumbnail("175x120").url), image.thumbnail("900x600").url, class: 'fancybox', rel: 'gallery' %>
      <% end %>
    </div>
  <% end %>

  <%= sidebar do %>
    <%= render 'shared/fb_like_box' %>
  <% end %>
<% end %>

app/views/shared/_banner.html.erb
<section id="banner" class="<%= random_banner_bg %>">
  <div class="heading-bg">&nbsp;</div>

  <%= render :partial => home_page? ? '/shared/banner/enhanced' : '/shared/banner/std' %>
  <div id="logo"><%= image_tag 'logos/white-trans.png' %></div>
</section>

app/views/shared/_carousel.html.erb
<div class="page">
  <%= raw carousel.content_for(:body) %>
  <p class="page-number"><%= formatted_carousel_page(carousel_counter) %></p>
</div>

app/views/shared/_fb_like_box.html.erb
<div class="fb-like-box" data-href="https://www.facebook.com/Soccerfives?fref=ts" data-width="290" data-show-faces="true" data-stream="true" data-border-color="#cecece" data-header="false"></div>

app/views/shared/_links.html.erb
<h2>Useful Links</h2>
<p>Below are some links you may find useful</p>
<div class="logos">
  <p><%= link_to image_tag('logos/mariners-link.png'), 'http://www.ccmariners.com.au', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/pele.png'), 'http://www.pele-sports.com.au', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/ruaridh.png'), 'http://www.ruaridh-currie.com', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/thecentralcoast.png'), 'http://www.thecentralcoast.com.au', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/internationalfootballschool.png'), 'http://www.internationalfootballschool.com', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/ccfootball.png'), 'http://www.ccfootball.com.au', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/facebook.png'), 'http://www.facebook.com/pages/Soccer5s/124555744270317', :target => '_blank' %></p>
  <p><%= link_to image_tag('logos/twitter.png'), 'http://twitter.com/soccer5s', :target => '_blank' %></p>
</div>

app/views/shared/_main_menu.html.erb
<ul id="main-menu">
  <li id="home-link"><%= link_to "Home", root_path %></li>
  <li id="what-link"><%= link_to "What is 5-a-side", what_path %></li>
  <li id="facility-link"><%= link_to "Facilities", facilities_path %></li>
  <li id="events-link"><%= link_to "Events", events_path %></li>
  <li id="training-link"><%= link_to "Training", training_path %></li>
  <li id="competition-link"><%= link_to "Competition", comp_path %></li>
  <li id="about-link"><%= link_to "About Us", about_path %></li>
  <li id="contact-link"><%= link_to "Contact", new_contact_path %></li>
</ul>

app/views/shared/_std_slogan.html.erb
<div id="slogan" class="std"><h1>Bringing 5-a-side Soccer To Australia</h1></div>

app/views/shared/banner/_enhanced.html.erb
<div id="slogan" class="enhanced">
  <h1>Bringing <span class="highlight">5-a-side Soccer</span> To Australia ALL WEATHER</h1>
</div>

<div id="notice">
  <h2><%= link_to "1 Bryant Drive", refinery.inquiries_new_inquiry_path(anchor: 'map') %>, Tuggerah at the Mariners Centre of Excellence</h2>
</div>

<div class="info">
  <p>
    For information on Soccer5s email <a href="mailto:info@soccer5s.com">info@soccer5s.com</a><br />
    call <span class="font-color-yellow">02 4355 4805</span>
  </p>
</div>

<div id="home_links">
  <%= link_to 'Leagues', "http://soccer-5s.ezleagues.ezfacility.com", class: "button", target: "_blank" %>
  <%= link_to 'Join a League', 'http://www.soccer5s.com/leagues/register', class: 'button' %>
</div>

app/views/shared/banner/_std.html.erb
<div id="slogan" class="std">
  <h1 class="title"><%= page_title %></h1>
</div>